### ISSUE TITLE
Smaller namespace / reducing verbosity

### ISSUE THREAD

**Issue by samhh** [js-choi/proposal-function-helpers#10]
The repeated use of `Function.` preceding every function helper call is going to get very verbose very quickly.

As evidence of this, in the fp-ts ecosystem it's common to import namespaces as acronyms, for example `TaskEither` might be imported as `TE`.

Where currently my code might look something like this:

```ts
compose(O.fold(constant(x), identity), O.map(f), O.fromNullable)
```

It's going to be a tough sell changing to this:

```ts
Function.compose(O.fold(Function.constant(x), Function.identity), O.map(f), O.fromNullable)
```

The simplest suggestion I have would be to change `Function` to `Fun` or `Fn`. Alternatively if we could somehow import from `Function` like we currently do for libraries that'd pretty much solve it - I'm not fully clued up on the state of various proposals at the moment, so perhaps I've missed something.

As a point of comparison against Haskell:

- `Function.compose` - `.` operator
- `Function.pipe` - `$` operator
- `Function.identity` - `id`
- `Function.constant` - `const`

**Comment by js-choi** [comment]
I think that, unfortunately, I would have a difficult time convincing the Committee that a wholly new global namespace object like `Fun` or `Fn` would be warranted. 

Is there a particular reason why destructuring the `Function` object wouldn’t fit your needs?

```js
const { compose, pipe, identity, constant } = Function;
const f = compose(O.fold(constant(x), identity), O.map(f), O.fromNullable);
```
After all, that wouldn’t be too different than how we already import things:
```js
import { compose, pipe, identity, constant } from 'fn-helpers';
const f = compose(O.fold(constant(x), identity), O.map(f), O.fromNullable);
```
I think that proposing a wholly new global namespace object like `Fun` or `Fn` would greatly reduce the probability that the Committee would advance this proposal. So I will probably stick and recommend that destructuring assignment. Hopefully that makes sense. (I’ll edit the explainer later to explain this.)

**Comment by samhh** [comment]
That works for me.

I'm having a slow day. :smile:
