### ISSUE TITLE
Considerations of the `Function.pipe()` semantics

### ISSUE THREAD

**Issue by Jopie64** [js-choi/proposal-function-helpers#9]
Hi,

I like to see some functional helpers being standardized, because now every functional lib has its own version of it. And especially now the [`|>` operator proposal](https://github.com/tc39/proposal-pipeline-operator) is heading in the, in my view, wrong direction, I think the `Function.pipe()` function would become especially important. So here are some considerations about that:

I'm used to the [`pipe()` semantics of ramda](https://ramdajs.com/docs/#pipe). This pipe has different semantics than the `Function.pipe()`, in that it returns a function instead of a value. And also the first argument of `R.pipe()` is a function, while in `Function.pipe()` it is a value (the subject). Actually the `R.pipe()` version is semantically equivalent to how `Function.compose()` is currently defined, except that the operations are reversed.

The current semantics of `Function.pipe()` can be usefull, but I think that there also needs to be a version with the `R.pipe()` semantics. You could argue that `Function.compose()` can be used instead, (which is arguably mathematically more correct) but that would require people to read from bottom to top, where in the rest of the code you read from top to bottom.

So I think it is important to also include a `pipe` function with `R.pipe()` semantics.

In fp-ts they have both versions: [`pipe()`](https://gcanti.github.io/fp-ts/modules/function.ts.html#pipe) with the current `Function.pipe()` semantics and [`flow()`](https://gcanti.github.io/fp-ts/modules/function.ts.html#flow) with the `R.pipe()` semantics.

Would it be an idea to add `Function.flow()` as well in this proposal?
Usage example:

```ts
['1', '2', '3'].map(Function.flow(
  toNumber,
  add(3),
  toString
));
// ['4', '5', '6']
```

**Comment by Avaq** [comment]
I think this might be, for the most part, a duplicate of #5. Much of the information shared here is also being organized in #6.

**Comment by Jopie64** [comment]
This seems to be a duplicate of the much more elaborate and better formulated issue #5. Sorry for the noise :)
